# docker compose up -d --build
name: romtech

services:
  web:
    build: ./web/
    ports:
      - "4200:4200"

    network_mode: "host"

  server:
    build: ./server/
    ports:
      - "3000:3000"
    network_mode: "host"

  db:
    build: ./server/SQL/
    ports:
      - "3306:3306"
    volumes:
      - ./server/SQL/mysql:/var/lib/mysql
    network_mode: "host"