# docker compose up -d --build

# docker compose down; git pull; docker compose up -d --build

# docker compose down; git pull;  rm -rf ./server/SQL/mysql/; docker compose up -d --build

# -----------------------------------------
# pull and run latest without seeding:
# docker compose down; git pull; sudo rm -rf ./server/SQL/mysql; mv ./server/SQL/10_seed_data.sql ~/Desktop/;  docker compose up -d --build; mv ~/Desktop/10_seed_data.sql ./server/SQL/

name: romtech

services:
  #web:
  #  build: ./web/
  #  # no need for ports when the network mdoe is set to "host"
  #  #ports:
  #  #  - "4200:4200"
  #  network_mode: "host"
  #  restart: always
  #  depends_on:
  #    - server

  server:
    #build: ./server/
    build: 
      dockerfile: ./server/Dockerfile
      context: ./
    #ports:
    #  - "3000:3000"
    network_mode: "host"
    restart: always
    depends_on:
      - db
    volumes:
      - ./server/uploads:/server/uploads

  db:
    build: ./server/SQL/
    # command: /bin/bash -c 'mysql -u root -p12345678 < /docker-entrypoint-initdb.d/create_db.sql'
    #ports:
    #  - "3306:3306"
    volumes:
      - ./server/SQL/mysql:/var/lib/mysql
    network_mode: "host"
    restart: always