const db = require('./db');
const helper = require('../helper');
const nodemailer = require("nodemailer");
const emailValidator = require('deep-email-validator');
const { logger } =  require('../logger');

async function validateAddress(emailAddress){
  const validationResult = await emailValidator.validate({
    email: emailAddress,
    sender: emailAddress,
    validateRegex: true,
    validateMx: true,
    validateTypo: true,
    validateDisposable: true,
    validateSMTP: false,
  });
  //console.dir(validationResult);
  if(validationResult){
    if(!validationResult.valid){
      const prefix = "Email address error: "
      if(!validationResult.validators.regex.valid){
        throw new Error(prefix + "Invalid address structure");    
      }
      if(!validationResult.validators.typo.valid){
        throw new Error(prefix + "Address was probably mistyped");    
      }
      if(!validationResult.validators.disposable.valid){
        throw new Error(prefix + "Address was generated by a disposable mailing service");    
      }
      if(!validationResult.validators.mx.valid){
        throw new Error(prefix + "Invalid MX records");    
      }
      if(!validationResult.validators.smtp.valid){
        throw new Error(prefix + "Unreachable SMTP servers");    
      }
      throw new Error(prefix + "Invalid address");
    }
  }
  return validationResult.valid;
}

/*
Message is sent as HTML.
To include images in the message:
Include in the attachments arg. Structure is:
[
  {
    filename: "screenshot.png",
    content: fs.readFileSync("/tmp/screenshot.png"),
    cid: "screenshot@example.com" //<- any unique id
  },
  ...
]

And  embedded in the message by cid:
<img src="cid:screenshot@example.com"/>
*/
async function sendMail(to, cc, bcc, subject, body, attachments=[], validateRecipientAddress=true) {

  logger.debug(`Sending email, To:${to}, from: ${process.env.EMAIL_USER}, subject: ${subject}, body:${body}`);

  if(validateRecipientAddress){
    if(to) {
      if(Array.isArray(to)) {
        to.forEach(async address => {if(address) await validateAddress(address);} );
      }
      else
      {
        await validateAddress(to);
      }
    }
    if(cc) {
      if(Array.isArray(cc)) {
        cc.forEach(async address => {if(address) await validateAddress(address);} );
      }
      else
      {
        await validateAddress(cc);
      }
    }
    if(bcc) {
      if(Array.isArray(bcc)) {
        bcc.forEach(async address => {if(address) await validateAddress(address);} );
      }
      else
      {
        await validateAddress(bcc);
      }
    }   
  }

  // 1. Create the transporter
  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.EMAIL_USER,     // your gmail
      pass: process.env.EMAIL_PASS      // the 16-char password
    }
  });

  let message = {
    from: process.env.EMAIL_FROM,
    to: to,
    subject: subject,
    html: body,
    attachments: attachments
  };

  let recipients_added = false;

  if(to){
    message["to"] = to;
    recipients_added = true;
  }

  if(cc){
    message["cc"] = cc;
    recipients_added = true;
  }

  if(bcc){
    message["bcc"] = bcc;
    recipients_added = true;
  }

  // 2. Send the email
  if(recipients_added) {
    await transporter.sendMail(message);
  }
}

//removes dots and anything after the + in the username of the email address, if the domain is gmail.com,
//to get the clean original reduced address
function reduceGmailAddress(email_address){
 return (email_address.toLowerCase().indexOf("gmail.com") > 0)?
    email_address.split("@")[0].replaceAll(".","").split("+")[0] + "@" + email_address.split("@")[1] :
    email_address;
}

module.exports = {
    validateAddress,
    sendMail,
    reduceGmailAddress
}