# Angular client app for Romtech for debugging purposes

FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    software-properties-common \
    wget \
    nano \
    curl

RUN mkdir /web
WORKDIR /web

ENV NVM_DIR=/root/.nvm \
    NODE_VERSION=22.0.0

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash \
    && . "$NVM_DIR/nvm.sh" \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

# Add NVM to PATH
ENV PATH="$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH"

RUN npm install -g @angular/cli@latest

CMD ["ng", "serve", "--host", "0.0.0.0", "--configuration=development"]